"use client";
import { useState } from "react";
import type { Data,Entity,Kind,Snapshot } from "@/lib/model";
import { Checkbox } from "@/components/ui/checkbox";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { DialogTitle,DialogDescription } from "@/components/ui/dialog";
export const days=["Dimanche","Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi"];
export const labels:Record<Kind,string>={shopping:"liste de courses",checklist:"checklist",item:"élément",product:"produit",note:"note",category:"catégorie",contact:"contact",electricity:"plage d’heures creuses",waste:"sortie de poubelles"};
export function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string}) { return <Select value={value||"none"} onValueChange={v=>onChange(v==="none"?"":v)}><SelectTrigger aria-label={label} className="w-full bg-white text-xs"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value||"none"} value={o.value||"none"}>{o.label}</SelectItem>)}</SelectContent></Select>; }
export function categoryOptions(entities:Entity[],exclude?:string) {
 const categories=entities.filter(e=>e.kind==="category");
 const options:{value:string;label:string}[]=[];const seen=new Set<string>();
 function walk(parent:string|undefined,prefix:string){for(const c of categories.filter(e=>e.data.parentId===parent)){if(seen.has(c.id)||c.id===exclude)continue;seen.add(c.id);options.push({value:c.id,label:prefix+String(c.data.name)});walk(c.id,prefix+"— ");}}
 walk(undefined,"");return options;
}
export default function EntityEditor({kind,entity,snapshot,onSave,busy,error}:{kind:Kind;entity?:Entity;snapshot:Snapshot;onSave:(data:Data)=>Promise<void>;busy:boolean;error:string}) {
 const [data,setData]=useState<Data>(entity?.data||{name:"",icon:kind==="shopping"?"basket":"check",reusable:false,content:"",color:kind==="waste"?"#e0b446":"purple",start:"22:00",end:"06:00",days:[0,1,2,3,4,5,6],weekday:2,reminder:"19:00",frequency:1,category:"",barcodes:[],phone:"",email:"",address:""});
 const update=(key:string,value:unknown)=>setData(d=>({...d,[key]:value}));
 const field=(key:string,label:string,type="text",required=false)=><label className="field">{label}<input type={type} value={String(data[key]||"")} required={required} onChange={e=>update(key,e.target.value)} maxLength={key==="name"?150:undefined}/></label>;
 return <><DialogTitle className="dialog-title">{entity?"Modifier":"Créer"} {labels[kind]}</DialogTitle><DialogDescription>Les modifications sont partagées avec votre foyer.</DialogDescription><form className="form-stack" onSubmit={async e=>{e.preventDefault();try{await onSave(data);}catch{}}}>{field("name",kind==="contact"?"Nom du contact":"Nom","text",true)}
 {(kind==="shopping"||kind==="checklist")&&<label className="field">Icône<Choice label="Icône" value={String(data.icon)} onChange={v=>update("icon",v)} options={[{value:"basket",label:"Panier"},{value:"carrot",label:"Marché"},{value:"home",label:"Maison"},{value:"check",label:"Tâches"},{value:"plane",label:"Voyage"},{value:"heart",label:"Famille"},{value:"bag",label:"Sac"}]}/></label>}
 {kind==="checklist"&&<><label className="check-field"><Checkbox checked={!!data.reusable} onCheckedChange={v=>update("reusable",!!v)}/>Réutiliser cette liste</label><p className="helper">Une liste réutilisable conserve les éléments cochés et peut être remise à zéro. Dans une liste éphémère, terminer une tâche la supprime.</p></>}
 {kind==="note"&&<><label className="field">Votre note<textarea value={String(data.content||"")} onChange={e=>update("content",e.target.value)} rows={8}/></label><label className="field">Couleur<Choice label="Couleur de la note" value={String(data.color||"purple")} onChange={v=>update("color",v)} options={[{value:"purple",label:"Violet"},{value:"yellow",label:"Jaune"},{value:"blue",label:"Bleu"}]}/></label></>}
 {kind==="product"&&<>{field("category","Rayon / catégorie")}<label className="field">Codes-barres (un par ligne)<textarea style={{minHeight:85}} value={(data.barcodes||[]).join("\n")} onChange={e=>update("barcodes",e.target.value.split(/\n/).map(v=>v.trim()).filter(Boolean))}/></label><p className="helper">Plusieurs codes peuvent désigner le même produit. Chaque code est unique dans le foyer.</p></>}
 {kind==="category"&&<label className="field">Catégorie parente<Choice label="Catégorie parente" value={data.parentId||""} onChange={v=>update("parentId",v||undefined)} options={[{value:"",label:"Aucune — catégorie principale"},...categoryOptions(snapshot.entities,entity?.id)]}/></label>}
 {kind==="contact"&&<>{field("phone","Téléphone","tel")}{field("email","Email","email")}{field("address","Adresse postale")}<label className="field">Catégorie<Choice label="Catégorie du contact" value={data.categoryId||""} onChange={v=>update("categoryId",v||undefined)} options={[{value:"",label:"Sans catégorie"},...categoryOptions(snapshot.entities)]}/></label></>}
 {kind==="electricity"&&<><div className="form-row">{field("start","Début des heures creuses","time",true)}{field("end","Fin des heures creuses","time",true)}</div><label className="field">Jours de début de la plage</label><div className="days-picker">{[1,2,3,4,5,6,0].map(d=><button type="button" key={d} className={"day-button "+((data.days||[]).includes(d)?"active":"")} aria-label={days[d]} aria-pressed={(data.days||[]).includes(d)} onClick={()=>update("days",(data.days||[]).includes(d)?data.days?.filter(v=>v!==d):[...(data.days||[]),d])}>{days[d].slice(0,2)}</button>)}</div><p className="helper">Une plage 22:00–06:00 se termine le lendemain. Les heures hors de ces plages sont des heures pleines. Fuseau : Europe/Paris.</p></>}
 {kind==="waste"&&<><div className="form-row"><label className="field">Jour de sortie<Choice label="Jour de sortie" value={String(data.weekday??2)} onChange={v=>update("weekday",Number(v))} options={[1,2,3,4,5,6,0].map(d=>({value:String(d),label:days[d]}))}/></label>{field("reminder","Heure du rappel","time",true)}</div><div className="form-row"><label className="field">Fréquence<Choice label="Fréquence" value={String(data.frequency||1)} onChange={v=>update("frequency",Number(v))} options={[1,2,3,4].map(f=>({value:String(f),label:f===1?"Chaque semaine":`Toutes les ${f} semaines`}))}/></label>{field("color","Couleur du bac","color")}</div>{Number(data.frequency)>1&&field("anchorDate","Date d’une première sortie","date",true)}<p className="helper">Indiquez le jour où vous sortez le bac, même si la collecte a lieu le lendemain matin.</p></>}
 {error&&<p role="alert" className="error-text">{error}</p>}<div className="modal-actions"><button disabled={busy} className="primary-button" type="submit">{busy?"Enregistrement…":"Enregistrer"}</button></div>
 {entity&&<p className="audit-text">Créé par {snapshot.members.find(m=>m.id===entity.createdBy)?.name||"un membre"} le {new Date(entity.createdAt).toLocaleDateString("fr-FR")} · Modifié le {new Date(entity.updatedAt).toLocaleString("fr-FR",{timeZone:"Europe/Paris"})}</p>}</form></>;
}
